export const projects = [
  {
    icon: "📦",
    title: "LostFound",
    description: "Sistema de Gestão de Itens Perdidos.",
    tags: ["Python", "JavaScript", "HTML/CSS", "MySQL"],
    link: "https://github.com/L3l4ck561/LostFound",
  },
  {
    icon: "💻",
    title: "SENAI+",
    description: "Sistema Web para Gerenciamento de Entrada e Saída de Alunos.",
    tags: ["Python", "JavaScript", "HTML/CSS", "MySQL", "Auditório & Logs"],
    link: "https://github.com/SergioPelais/SENAI-",
  },
  {
    icon: "🖩",
    title: "Calculadora",
    description: "Feito com troca de tema (DarkMode) e tratamento de erro.",
    tags: ["HTML", "CSS", "JS"],
    link: "https://l3l4ck561.github.io/Projeto-2Calculadora/",
  },
  {
    icon: "📅",
    title: "RotaRotina",
    description: "Agenda funcional com armazenamento em LocalStorage",
    tags: ["React(Vite)", "Mui", "Tailwind", "TypeScript"],
    link: "https://github.com/L3l4ck561/RotaRotina",
  },
  {
    icon: "🎮",
    title: "Toca Da Coruja",
    description: "Game desenvolvido num evento GameJam",
    tags: ["Construct2"],
    link: "https://birdgamejam.itch.io/a-toca-da-coruja",
  },
  {
    icon: "🖹",
    title: "Orçamendo doméstico",
    description: "",
    tags: ["Excel", "VBA"],
    link: "https://drive.google.com/file/d/1yVLD50er0jScJPfo28-cvXz3vMi_-4OG/view?usp=sharing",
  },
  {
    icon: "🎂",
    title: "Aniversariantes do mês",
    description: "",
    tags: ["Excel", "VBA"],
    link: "https://drive.google.com/file/d/1vZn39yE2lt1dLzapWCnkMaslI75qtJgn/view?usp=sharing",
  },
  {
    icon: "🖩",
    title: "Calculadora",
    description: "",
    tags: ["Excel", "VBA"],
    link: "https://drive.google.com/file/d/1mw73TuBY_0yO9lhv0Hq_DXs0kX3JWVoX/view?usp=sharing",
  },
  {
    icon: "#",
    title: "Jogo da velha",
    description: "",
    tags: ["Excel", "VBA"],
    link: "https://drive.google.com/file/d/1I1nfcxq5fdCzJPSQuOsDCaKCdoMg0TXR/view?usp=sharing",
  },
  {
    icon: "♟️",
    title: "Xadrez",
    description: "",
    tags: ["Excel", "VBA"],
    link: "https://drive.google.com/file/d/1Cj34R2yMhZtUXXLoesdcYgSW6dJ8Ctmy/view?usp=sharing#",
  },
];